/* system1/chat.jsx — chat thread + composer with paperclip + artifact references */

const Avatar = ({ role, opId }) => {
  if (role === 'bot') return <div className="msg__avatar"><AEyeMark /></div>;
  if (role === 'instructor') return <div className="msg__avatar" title="Instructor">TA</div>;
  return <div className="msg__avatar">{(opId || 'OP').slice(-2)}</div>;
};

// very lightweight markdown-ish formatter for chat bubbles
const formatBubble = (text) =>
  text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(/\*\*([^*]+)\*\*/g, '<strong style="color:var(--cream)">$1</strong>')
    .replace(/\*([^*]+)\*/g, '<em>$1</em>');

const ArtifactRef = ({ doc, onOpen }) => (
  <button className="artifact-ref" onClick={() => onOpen(doc.id)}>
    <span className="artifact-ref__icon">{doc.type === 'md' ? '▤' : '▣'}</span>
    <span className="artifact-ref__body">
      <span className="artifact-ref__title">{doc.name}</span>
      <span className="artifact-ref__meta">
        {doc.type.toUpperCase()} · {doc.lines || (doc.content || '').split('\n').length} LINES
        {doc.author === 'bot' ? ' · GENERATED BY TEACHERBOT' : ' · ATTACHED BY OPERATIVE'}
      </span>
    </span>
    <span className="artifact-ref__open">OPEN ▸</span>
  </button>
);

const AttachmentChip = ({ doc, onOpen }) => (
  <button className="msg__attachment" onClick={() => onOpen(doc.id)}>
    <span className="msg__attachment__icon">▣</span>
    <span className="msg__attachment__name">{doc.name}</span>
    <span className="msg__attachment__meta">
      · {doc.type.toUpperCase()} · {(doc.content || '').split('\n').length} LINES
    </span>
  </button>
);

const Message = ({ msg, opId, onOpenDoc }) => {
  const { role, text, time, streaming, attachment, artifact, authorName } = msg;
  return (
    <div className={'msg msg--' + role}>
      <Avatar role={role} opId={role === 'instructor' ? 'TA' : opId} />
      <div className="msg__body">
        <div className="msg__meta">
          {role === 'bot'
            ? <>TEACHERBOT · {time}</>
            : role === 'instructor'
              ? <>{authorName || 'INSTRUCTOR'} · {time} <span className="role-tag">CO-PILOT</span></>
              : <>OPERATIVE {opId} · {time}</>}
        </div>

        {attachment && <AttachmentChip doc={attachment} onOpen={onOpenDoc} />}

        <div
          className="msg__bubble"
          dangerouslySetInnerHTML={{
            __html: formatBubble(text)
              + (streaming ? '<span style="color:var(--amber); animation: cursor-blink 1s steps(2) infinite;">▌</span>' : '')
          }}
        />

        {artifact && !streaming && <ArtifactRef doc={artifact} onOpen={onOpenDoc} />}
      </div>
    </div>
  );
};

const PaperclipIcon = () => (
  <svg viewBox="0 0 24 24" fill="none" strokeWidth="1.5" strokeLinecap="square" strokeLinejoin="miter">
    <path d="M21 12.5L13.5 20A5.5 5.5 0 0 1 5.74 12.24L13 5a3.5 3.5 0 0 1 5 5l-7.3 7.3a1.5 1.5 0 1 1-2.12-2.12L14.5 9.5" />
  </svg>
);

const Composer = ({ onSend, disabled, role, attachments, onAttach, onRemoveAttach, onPasteCode }) => {
  const [value, setValue] = React.useState('');
  const ref = React.useRef();

  const submit = () => {
    const trimmed = value.trim();
    if ((!trimmed && attachments.length === 0) || disabled) return;
    onSend(trimmed);
    setValue('');
    if (ref.current) ref.current.style.height = 'auto';
  };

  const onKey = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      submit();
    }
  };

  const onChange = (e) => {
    setValue(e.target.value);
    const el = e.target;
    el.style.height = 'auto';
    el.style.height = Math.min(el.scrollHeight, 140) + 'px';
  };

  const onPaste = (e) => {
    const pasted = e.clipboardData.getData('text');
    // auto-promote long code-ish pastes (≥6 lines or 400 chars)
    if (pasted && (pasted.split('\n').length >= 6 || pasted.length > 400)) {
      e.preventDefault();
      onPasteCode(pasted);
    }
  };

  const placeholder = disabled
    ? 'Teacherbot is streaming a reply …'
    : role === 'instructor'
      ? 'Post as INSTRUCTOR co-pilot. Operatives will see your message tagged.'
      : 'Ask Teacherbot. Paperclip ▸ attach a file. Paste long code to auto-promote.';

  return (
    <div className="composer">
      <div className="composer__attachments">
        {attachments.map(a => (
          <span className="attach-chip" key={a.id}>
            <span className="attach-chip__icon">▣</span>
            {a.name}
            <button className="attach-chip__remove" onClick={() => onRemoveAttach(a.id)} title="Remove">×</button>
          </span>
        ))}
      </div>
      <div className="composer__wrap">
        <span className="composer__prompt">&gt;</span>
        <textarea
          ref={ref}
          className="composer__input"
          rows="1"
          value={value}
          placeholder={placeholder}
          onChange={onChange}
          onKeyDown={onKey}
          onPaste={onPaste}
          disabled={disabled}
        />
        <button className="composer__icon-btn" onClick={onAttach} title="Attach a document" aria-label="Attach">
          <PaperclipIcon />
        </button>
        <button className="composer__send" onClick={submit} disabled={disabled || (!value.trim() && attachments.length === 0)}>
          {role === 'instructor' ? 'POST ↩' : 'SEND ↩'}
        </button>
      </div>
      <div className="composer__hint">
        <span>↩ send · ⇧↩ newline · paste &gt;6 lines → side frame</span>
        <span style={{ color: 'var(--cream-muted)' }}>All conversations logged for instructor review.</span>
      </div>
    </div>
  );
};

const EmptyState = ({ groupName, onSuggest }) => (
  <div className="empty">
    <div className="empty__mark"><AEyeMark /></div>
    <div className="empty__title">Teacherbot</div>
    <div className="empty__sub">at your service</div>
    <div className="empty__hint">
      Ready to help <strong style={{ color: 'var(--cream)' }}>{groupName}</strong> ship your capstone.
      Attach code · ask a question · paste a stack trace.
    </div>
    <div className="empty__suggestions">
      <button className="suggestion" onClick={() => onSuggest('My Flask route is returning 404. I attached the file.')}>
        <strong>Debug</strong>
        My Flask route is returning 404 — what should I check first?
      </button>
      <button className="suggestion" onClick={() => onSuggest('Explain Flask sessions like I have never seen them before.')}>
        <strong>Concept</strong>
        Explain Flask sessions like I've never seen them.
      </button>
      <button className="suggestion" onClick={() => onSuggest('Draft a sprint plan markdown for our next two weeks.')}>
        <strong>Artifact</strong>
        Draft a sprint plan for the next two weeks.
      </button>
      <button className="suggestion" onClick={() => onSuggest('Review my login route and suggest changes.')}>
        <strong>Pair</strong>
        Review my login route inline.
      </button>
    </div>
  </div>
);

const ChatThread = ({ messages, streaming, opId, group, role, onSend, onOpenDoc, attachments, onAttach, onRemoveAttach, onPasteCode, presence }) => {
  const threadRef = React.useRef();

  React.useEffect(() => {
    if (threadRef.current) {
      threadRef.current.scrollTop = threadRef.current.scrollHeight;
    }
  });

  return (
    <main className="chat">
      <div className="chat__topbar">
        <div className="chat__title">
          <span className="chat__title-mark">{group.code}</span>
          <div className="chat__title-text">
            <span>{group.alias} <span style={{ color: 'var(--cream-muted)', fontWeight: 400, fontSize: 12 }}>· {group.project}</span></span>
            <small>CONTEXT INJECTED · {group.members} OPERATIVES · {group.clearance} CLEARANCE</small>
          </div>
        </div>
        <span className={'pill ' + (presence ? 'pill--editing' : streaming ? 'pill--streaming' : 'pill--online')}>
          <span className="pill__dot" />{presence ? 'EDITING DOC' : streaming ? 'STREAMING' : 'READY'}
        </span>
      </div>

      {messages.length === 0 ? (
        <EmptyState groupName={group.alias} onSuggest={onSend} />
      ) : (
        <div className="chat__thread" ref={threadRef}>
          {messages.map(m => (
            <Message key={m.id} msg={m} opId={opId} onOpenDoc={onOpenDoc} />
          ))}
        </div>
      )}

      <Composer
        onSend={onSend}
        disabled={streaming}
        role={role}
        attachments={attachments}
        onAttach={onAttach}
        onRemoveAttach={onRemoveAttach}
        onPasteCode={onPasteCode}
      />
    </main>
  );
};

Object.assign(window, { ChatThread, Message, EmptyState, Composer, ArtifactRef });
