"""baseline: groups, conversations, messages

The schema as `db.create_all()` left it, captured so Alembic owns it from
here. Autogenerated against an empty database and not hand-edited — it is
meant to be exactly what the models declare, so a diff against models.py is
a bug in one of the two.

This runs clean against the new Pro database, which starts empty. It is
*not* safe against the old free-tier database, where these three tables
already exist unknown to Alembic; that one would have needed a one-time
`flask db stamp head` first. See ADR-0006 — starting fresh is what let us
skip that step, and it is the reason this revision has no guards in it.

Revision ID: 69d2bbe0a8f9
Revises:
Create Date: 2026-07-29 00:25:31.240203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69d2bbe0a8f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('clearance_level', sa.String(length=20), nullable=False),
    sa.Column('token_budget', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('conversations')
    op.drop_table('groups')
    # ### end Alembic commands ###
